from . import res_company
from . import res_config_settings
from . import ir_http
from . import ir_ui_view
from . import ir_act_window_view
from . import hr_attendance_geofence
from . import hr_attendance
from . import hr_employee
from . import hr_leave_type
from . import hr_work_entry
from . import hr_res_montaj_tipi
from . import hr_work_res_montaj
